sonar.organization=amarsaleem333
sonar.projectKey=php-todo
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
sonar.php.exclusions=**/vendor/**
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml